import { format, addDays, subDays } from "date-fns";
import type { Task, Habit } from "@/types";

const today = format(new Date(), "yyyy-MM-dd");
const yesterday = format(subDays(new Date(), 1), "yyyy-MM-dd");
const tomorrow = format(addDays(new Date(), 1), "yyyy-MM-dd");

export const demoTasks: Task[] = [
  {
    id: "1",
    title: "Review design mockups",
    description: "Check Figma files for the new dashboard and provide feedback.",
    priority: "high",
    dueDate: today,
    dueTime: "09:00",
    tags: ["work", "design"],
    status: "done",
    order: 0,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    completedAt: new Date().toISOString(),
  },
  {
    id: "2",
    title: "Team standup",
    description: "Daily sync with the product team.",
    priority: "medium",
    dueDate: today,
    dueTime: "10:00",
    tags: ["work", "meeting"],
    status: "in_progress",
    order: 1,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "3",
    title: "Ship auth flow",
    description: "Deploy the new authentication flow to staging.",
    priority: "high",
    dueDate: today,
    dueTime: "14:00",
    tags: ["work", "engineering"],
    status: "todo",
    order: 2,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "4",
    title: "Write weekly report",
    description: "Summarize progress and blockers for stakeholders.",
    priority: "medium",
    dueDate: today,
    dueTime: "16:00",
    tags: ["work"],
    status: "todo",
    order: 3,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "5",
    title: "Evening workout",
    description: "30 min run or gym session.",
    priority: "low",
    dueDate: today,
    dueTime: "18:00",
    tags: ["health", "personal"],
    status: "todo",
    order: 4,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "6",
    title: "Plan tomorrow",
    description: "Review calendar and set top 3 priorities.",
    priority: "low",
    dueDate: today,
    dueTime: "21:00",
    tags: ["planning"],
    status: "todo",
    order: 5,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "7",
    title: "Client call - Project Alpha",
    priority: "high",
    dueDate: tomorrow,
    dueTime: "11:00",
    tags: ["work", "meeting"],
    status: "todo",
    order: 0,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "8",
    title: "Read 20 pages",
    description: "Continue with 'Atomic Habits'.",
    priority: "low",
    dueDate: yesterday,
    dueTime: "20:00",
    tags: ["personal", "reading"],
    status: "done",
    order: 0,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    completedAt: new Date().toISOString(),
  },
];

export const demoHabits: Habit[] = [
  {
    id: "h1",
    name: "Morning journal",
    emoji: "📝",
    streak: 5,
    completedDates: [
      today,
      ...Array.from({ length: 4 }, (_, i) =>
        format(subDays(new Date(), i + 1), "yyyy-MM-dd")
      ),
    ],
    createdAt: new Date().toISOString(),
  },
  {
    id: "h2",
    name: "No phone before 9am",
    emoji: "📵",
    streak: 3,
    completedDates: [today, yesterday, format(subDays(new Date(), 2), "yyyy-MM-dd")],
    createdAt: new Date().toISOString(),
  },
  {
    id: "h3",
    name: "10k steps",
    emoji: "🚶",
    streak: 12,
    completedDates: [today],
    createdAt: new Date().toISOString(),
  },
];
